version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: twa-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock_trace
      MYSQL_USER: developer
      MYSQL_PASSWORD: developerPwd